### ISSUE TITLE
wrong values

### ISSUE THREAD

**Issue by theArcher73** [meekm/LoRaSoundkit#4]
Hi,

I have trouble with the measurements. When I start the sensor I get correct values. 
After 2-3 measurments the display switch to a scarry pricture.
Also over LoRa I get from this moment static values for each data-transmission.

so I have the following pic:

|        |avg |min | max
|-----|-----|-----|-----|
|       |     |     |     |
| 4B(C)|-inf |-inf | -379.| 
| 2B(Z)|-inf |-inf | -379.|
| 3   |     |     |     |
|TTN  |ok   |     |     |     

After a reboot thesame effect.

Do you know this effects?

Thx,
Steffen

**Comment by meekm** [comment]
Hi,
These values I recognize, when I made a mistake in wiring the MEMS.  In your situation in the begin the values are correct, so I Think it is not the wiring, but maybe a weak power supply. 
Try to comment out the loraSend (2 places in the .ino file).  The loraSend takes some power.

**Comment by theArcher73** [comment]
Typical Problem between chair and solder iron. GPIO35 should be used, not GPIO39 🙈

I found the mistake while shortening all wires. It works, thx and sorry. 

Now I will wait that TTN ok appears, what's are the reasons for the message TTN fail, while I can see the right values in the TTN-Server?

Steffen

**Comment by meekm** [comment]
I checked the code, the TTN fail/Ok  is one cycle behind. This can be improved in the next version.
