### ISSUE TITLE
Frequency calculations

### ISSUE THREAD

**Issue by rdkluijv** [meekm/LoRaSoundkit#6]
I'm lost when I look at the frequency calculation.
First: 
With 2048 samples multiple by 11 is 22528. Why use 22628?
Second:
With 22628 the maximum frequency that can be detected is 22628 / 2 = 11314 Hz. (Shannon)
With a 2048 length vector from the FFT I would expect a resolution of 5,5 Hz.
What's wrong with my calculation?

**Comment by meekm** [comment]
Answer 1:
The reason why this sample frequency has been chosen, is to map the bins nicely around the center frequency of the octaves. Thus measuring the energy of octave 31,25 Hz is the sum of exactly bin 1 and bin 2, which is the frequency range 22Hz to 44Hz. The measuring of octave 62,5 Hz is the sum of the energy in bin 3 up to 6, which is the frequency range 44Hz to 88Hz etc ...  

Answer 2
Correct, te highest frequency is sample frequency /2

Answer 3
The resolution is the bin size, which is sample frequency devided by buffersize, which is 22628/2048 is 11 Hz
