### ISSUE TITLE
Mems sleep mode

### ISSUE THREAD

**Issue by rdkluijv** [meekm/LoRaSoundkit#7]
All the microphones go in to sleep mode after not receiving a clock. When they start getting a clock it takes a while for the samples to be valid. I can't find the code where those samples are removed. Is that not necessary?

**Comment by meekm** [comment]
According me, the microphone goes never into sleep. The sensor is measuring continuously.
Do you think, the code is not complete, and samples must be removed?
There are no hicks in the sound when sending the samples to a wave file, and listen to it.
